FROM markadams/chromium-xvfb

RUN apt-get update && \
    apt-get -y install openjdk-11-jdk &&\
    apt-get -y install wget &&\
    apt-get -y install zip &&\
    apt-get -y install unzip &&\
    apt-get -y install git &&\
    apt-get -y install ssh

RUN wget https://services.gradle.org/distributions/gradle-6.4.1-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-*.zip

ENV GRADLE_HOME=/opt/gradle/gradle-6.4.1
ENV PATH=${GRADLE_HOME}/bin:${PATH}